import { Body, Controller, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { IsBoolean, IsEnum, IsInt, IsOptional, IsString, Max, Min } from 'class-validator';
import { CertificationStatus, MerchantStatus, QualificationStatus, QualificationType } from '@prisma/client';
import { RequirePermissions } from '../../common/permissions.decorator';
import { PermissionsGuard } from '../../common/permissions.guard';
import { JwtAccessGuard } from '../auth/jwt-access.guard';
import { MerchantsService } from './merchants.service';
class QueryDto { @IsOptional() @IsInt() @Min(1) page?:number; @IsOptional() @IsInt() @Min(1) @Max(100) pageSize?:number; @IsOptional() @IsString() keywords?:string; @IsOptional() @IsString() province?:string; @IsOptional() @IsString() city?:string; @IsOptional() @IsEnum(MerchantStatus) status?:MerchantStatus; @IsOptional() @IsEnum(CertificationStatus) certificationStatus?:CertificationStatus; }
class StatusDto { @IsEnum(MerchantStatus) status!:MerchantStatus; }
class ReviewDto { @IsEnum(CertificationStatus) certificationStatus!:CertificationStatus; @IsOptional() @IsString() certificationRemark?:string; }
class MerchantDto { @IsString() companyName!: string; @IsOptional() @IsString() shortName?: string; @IsString() contactName!: string; @IsString() contactPhone!: string; @IsOptional() @IsString() province?: string; @IsOptional() @IsString() city?: string; @IsOptional() @IsString() address?: string; @IsOptional() @IsString() unifiedSocialCreditCode?: string; @IsOptional() @IsString() legalRepresentative?: string; @IsOptional() @IsString() registeredCapital?: string; @IsOptional() @IsString() establishmentDate?: string; @IsOptional() @IsInt() @Min(0) employeeCount?: number; @IsOptional() @IsString() factoryArea?: string; @IsOptional() @IsString() website?: string; @IsOptional() @IsString() businessScope?: string; @IsOptional() @IsString() deliveryLocation?: string; @IsOptional() @IsInt() @Min(0) businessYears?: number; @IsOptional() @IsBoolean() supportsCustomization?: boolean; }
class QualificationDto { @IsEnum(QualificationType) type!: QualificationType; @IsString() url!: string; } class QualificationReviewDto { @IsEnum(QualificationStatus) status!: QualificationStatus; @IsOptional() @IsString() remark?: string; }
@ApiTags('merchants') @ApiBearerAuth() @UseGuards(JwtAccessGuard, PermissionsGuard) @Controller('merchants')
export class MerchantsController { constructor(private readonly merchants:MerchantsService) {} @Get() @RequirePermissions('merchant:read') page(@Query() q:QueryDto){return this.merchants.page(q)} @Get(':id') @RequirePermissions('merchant:read') detail(@Param('id')id:string){return this.merchants.detail(id)} @Post() @RequirePermissions('merchant:read') create(@Body() dto: MerchantDto,@Req() req:any){return this.merchants.create(dto,req.user.userId)} @Patch(':id') @RequirePermissions('merchant:read') update(@Param('id')id:string,@Body()dto:Partial<MerchantDto>,@Req()req:any){return this.merchants.update(id,dto,req.user.userId)} @Post(':id/qualifications') @RequirePermissions('merchant:read') qualification(@Param('id') id:string,@Body()dto:QualificationDto){return this.merchants.addQualification(id,dto)} @Patch('qualifications/:id/review') @RequirePermissions('merchant:approve') reviewQualification(@Param('id')id:string,@Body()dto:QualificationReviewDto,@Req()req:any){return this.merchants.reviewQualification(id,dto.status,dto.remark,req.user.userId)} @Patch(':id/status') @RequirePermissions('merchant:update') status(@Param('id')id:string,@Body()d:StatusDto,@Req() req:any){return this.merchants.updateStatus(id,d.status,req.user.userId)} @Patch(':id/certification') @RequirePermissions('merchant:approve') review(@Param('id')id:string,@Body()d:ReviewDto,@Req() req:any){return this.merchants.review(id,d.certificationStatus,d.certificationRemark,req.user.userId)} }
