import { Injectable, NotFoundException } from '@nestjs/common';
import { CertificationStatus, MerchantStatus, Prisma, QualificationStatus, QualificationType } from '@prisma/client';
import { PrismaService } from '../../common/prisma.service';
import { AuditLogsService } from '../audit-logs/audit-logs.service';
@Injectable()
export class MerchantsService {
  constructor(private readonly prisma: PrismaService, private readonly audits: AuditLogsService) {}
  async page(query: { page?: number; pageSize?: number; keywords?: string; province?: string; city?: string; status?: MerchantStatus; certificationStatus?: CertificationStatus }) {
    const page = Math.max(1, query.page ?? 1), pageSize = Math.min(100, Math.max(1, query.pageSize ?? 20));
    const where: Prisma.MerchantWhereInput = { ...(query.status ? { status: query.status } : {}), ...(query.certificationStatus ? { certificationStatus: query.certificationStatus } : {}), ...(query.province ? { province: query.province } : {}), ...(query.city ? { city: query.city } : {}), ...(query.keywords ? { OR: [{ companyName: { contains: query.keywords } }, { shortName: { contains: query.keywords } }] } : {}) };
    const [items, total] = await this.prisma.$transaction([this.prisma.merchant.findMany({ where, skip:(page-1)*pageSize, take:pageSize, orderBy:{ createdAt:'desc' } }), this.prisma.merchant.count({ where })]);
    return { items, page, pageSize, total };
  }
  async detail(id: string) { const row = await this.prisma.merchant.findUnique({ where:{id}, include:{ qualifications:true, products:{ where:{status:'ON_SHELF'}, include:{skus:true,images:true} } } }); if (!row) throw new NotFoundException('商家不存在'); return row; }
  async create(input: any, adminId: string) { const data = this.normalizeInput(input); const merchant = await this.prisma.merchant.create({ data: { ...data, status: 'ENABLED', certificationStatus: 'APPROVED', certificationRemark: '后台管理员手动新增，免认证审核' } }); await this.audits.write(adminId, 'merchant.create', 'Merchant', merchant.id, { companyName: merchant.companyName }); return merchant; }
  async update(id: string, input: any, adminId: string) { const before = await this.exists(id); const data = this.normalizeInput(input); const merchant = await this.prisma.merchant.update({ where: { id }, data }); await this.audits.write(adminId, 'merchant.update', 'Merchant', id, { before: { companyName: before.companyName, contactName: before.contactName, contactPhone: before.contactPhone }, after: input }); return merchant; }
  async addQualification(merchantId: string, input: { type: QualificationType; url: string }) { await this.exists(merchantId); return this.prisma.merchantQualification.create({ data: { merchantId, ...input } }); }
  async reviewQualification(id: string, status: QualificationStatus, remark: string | undefined, adminId: string) { const qualification = await this.prisma.merchantQualification.findUnique({ where: { id } }); if (!qualification) throw new NotFoundException('资质附件不存在'); const result = await this.prisma.merchantQualification.update({ where: { id }, data: { status, remark, reviewedById: adminId, reviewedAt: new Date() } }); await this.audits.write(adminId, 'merchant.qualification.review', 'MerchantQualification', id, { merchantId: qualification.merchantId, status, remark }); return result; }
  async updateStatus(id: string, status: MerchantStatus, adminId?: string) { const before = await this.exists(id); const result = await this.prisma.merchant.update({where:{id},data:{status}}); await this.audits.write(adminId, 'merchant.status.update', 'Merchant', id, { from: before.status, to: status }); return result; }
  async review(id: string, certificationStatus: CertificationStatus, certificationRemark?: string, adminId?: string) { const before = await this.exists(id); const result = await this.prisma.merchant.update({where:{id},data:{certificationStatus,certificationRemark}}); await this.audits.write(adminId, 'merchant.certification.review', 'Merchant', id, { from: before.certificationStatus, to: certificationStatus, certificationRemark }); return result; }
  private async exists(id:string) { const row=await this.prisma.merchant.findUnique({where:{id}}); if(!row) throw new NotFoundException('商家不存在'); return row; }
  private normalizeInput(input: any) { const { unifiedSocialCreditCode, legalRepresentative, registeredCapital, establishmentDate, employeeCount, factoryArea, website, businessScope, ...data } = input; const profile = Object.fromEntries(Object.entries({ unifiedSocialCreditCode, legalRepresentative, registeredCapital, establishmentDate, employeeCount, factoryArea, website, businessScope }).filter(([, value]) => value !== undefined && value !== '')); return { ...data, ...(Object.keys(profile).length ? { mainProducts: profile } : {}) }; }
}
