import { Body, Controller, Get, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import { IsArray, IsBoolean, IsEnum, IsInt, IsObject, IsOptional, IsString, Max, Min, ValidateNested } from 'class-validator';
import { ImageType, ProductStatus, SupplyType } from '@prisma/client';
import { Type } from 'class-transformer';
import { RequirePermissions } from '../../common/permissions.decorator'; import { PermissionsGuard } from '../../common/permissions.guard'; import { JwtAccessGuard } from '../auth/jwt-access.guard'; import { ProductsService } from './products.service';
class QueryDto {@IsOptional()@IsInt()@Min(1)page?:number;@IsOptional()@IsInt()@Min(1)@Max(100)pageSize?:number;@IsOptional()@IsString()keywords?:string;@IsOptional()@IsString()merchantId?:string;@IsOptional()@IsString()categoryId?:string;@IsOptional()@IsEnum(ProductStatus)status?:ProductStatus}
class SkuDto {@IsString()specName!:string;@IsString()specValue!:string;@IsString()skuCode!:string;@IsInt()@Min(0)priceCent!:number;@IsOptional()@IsInt()@Min(1)minOrderQuantity?:number;@IsOptional()@IsInt()@Min(0)stockQuantity?:number;@IsOptional()@IsBoolean()enabled?:boolean} class ImageDto {@IsString()url!:string;@IsOptional()@IsEnum(ImageType)type?:ImageType;@IsOptional()@IsInt()@Min(0)sortOrder?:number} class ProductDto {@IsOptional()@IsString()merchantId?:string;@IsOptional()@IsString()categoryId?:string;@IsOptional()@IsString()name?:string;@IsOptional()@IsString()model?:string;@IsOptional()@IsString()brand?:string;@IsOptional()@IsString()origin?:string;@IsOptional()@IsString()material?:string;@IsOptional()@IsString()processingMethod?:string;@IsOptional()@IsString()qualityStandard?:string;@IsOptional()@IsString()unit?:string;@IsOptional()@IsString()packaging?:string;@IsOptional()@IsString()supplyCapacity?:string;@IsOptional()@IsString()shortDescription?:string;@IsOptional()@IsString()detailContent?:string;@IsOptional()@IsObject()detailAttributes?:Record<string,string>;@IsOptional()@IsObject()tradeInfo?:Record<string,string>;@IsOptional()@IsString()mainImage?:string;@IsOptional()@IsEnum(SupplyType)supplyType?:SupplyType;@IsOptional()@IsInt()@Min(1)deliveryDays?:number;@IsOptional()@IsInt()@Min(1)minOrderQuantity?:number;@IsOptional()@IsArray()@ValidateNested({each:true})@Type(()=>SkuDto)skus?:SkuDto[];@IsOptional()@IsArray()@ValidateNested({each:true})@Type(()=>ImageDto)images?:ImageDto[]}
class ReviewDto {@IsBoolean()approved!:boolean;@IsOptional()@IsString()rejectionReason?:string} class ShelfDto {@IsBoolean()onShelf!:boolean}
@ApiTags('products')@ApiBearerAuth()@UseGuards(JwtAccessGuard,PermissionsGuard)@Controller('products') export class ProductsController{constructor(private readonly products:ProductsService){}@Get()@RequirePermissions('product:read')page(@Query()q:QueryDto){return this.products.page(q)}@Get(':id')@RequirePermissions('product:read')detail(@Param('id')id:string){return this.products.detail(id)}@Post()@RequirePermissions('product:create')create(@Body()d:ProductDto){return this.products.create(d as ProductDto & {merchantId:string;categoryId:string;name:string})}@Patch(':id')@RequirePermissions('product:update')update(@Param('id')id:string,@Body()d:ProductDto){return this.products.update(id,d)}@Patch(':id/review')@RequirePermissions('product:approve')review(@Param('id')id:string,@Body()d:ReviewDto){return this.products.review(id,d.approved,d.rejectionReason)}@Patch(':id/shelf')@RequirePermissions('product:publish')shelf(@Param('id')id:string,@Body()d:ShelfDto){return this.products.shelf(id,d.onShelf)}}
