import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { ImageType, Prisma, ProductStatus, SupplyType } from '@prisma/client';
import { PrismaService } from '../../common/prisma.service';
@Injectable() export class ProductsService {
 constructor(private readonly prisma:PrismaService){}
 async page(q:{page?:number;pageSize?:number;keywords?:string;merchantId?:string;categoryId?:string;status?:ProductStatus}){const page=Math.max(1,q.page??1),pageSize=Math.min(100,Math.max(1,q.pageSize??20));const where:Prisma.ProductWhereInput={deletedAt:null,...(q.status?{status:q.status}:{}),...(q.merchantId?{merchantId:q.merchantId}:{}),...(q.categoryId?{categoryId:q.categoryId}:{}),...(q.keywords?{name:{contains:q.keywords}}:{})};const[items,total]=await this.prisma.$transaction([this.prisma.product.findMany({where,skip:(page-1)*pageSize,take:pageSize,orderBy:{createdAt:'desc'},include:{merchant:true,category:true,skus:true,images:true}}),this.prisma.product.count({where})]);return{items,page,pageSize,total}}
 async detail(id:string){const row=await this.prisma.product.findFirst({where:{id,deletedAt:null},include:{merchant:true,category:true,skus:true,images:true}});if(!row)throw new NotFoundException('商品不存在');return row}
 async create(input:any){await this.assertMerchantAndCategory(input.merchantId,input.categoryId);const{skus=[],images=[],brand,origin,material,processingMethod,qualityStandard,unit,packaging,supplyCapacity,tradeInfo,detailAttributes,...data}=input;const detailContent=this.composeDetail(data.detailContent,{brand,origin,material,processingMethod,qualityStandard,unit,packaging,supplyCapacity,...(tradeInfo||{}),...(detailAttributes||{})});return this.prisma.product.create({data:{...data,detailContent,status:'DRAFT',skus:{create:skus},images:{create:images}},include:{skus:true,images:true}})}
 async update(id:string,input:any){const current=await this.detail(id);await this.assertMerchantAndCategory(input.merchantId??current.merchantId,input.categoryId??current.categoryId);const{skus,images,brand,origin,material,processingMethod,qualityStandard,unit,packaging,supplyCapacity,tradeInfo,detailAttributes,...data}=input;const detailContent=this.composeDetail(data.detailContent,{brand,origin,material,processingMethod,qualityStandard,unit,packaging,supplyCapacity,...(tradeInfo||{}),...(detailAttributes||{})});return this.prisma.product.update({where:{id},data:{...data,detailContent,status:current.status==='ON_SHELF'?'OFF_SHELF':'DRAFT',...(skus?{skus:{deleteMany:{},create:skus}}:{}),...(images?{images:{deleteMany:{},create:images}}:{})},include:{skus:true,images:true}})}
 async review(id:string,approved:boolean,rejectionReason?:string){await this.detail(id);if(!approved&&!rejectionReason)throw new BadRequestException('驳回时必须填写原因');return this.prisma.product.update({where:{id},data:{status:approved?'APPROVED':'REJECTED',rejectionReason:approved?null:rejectionReason}})}
 async shelf(id:string,onShelf:boolean){const row=await this.detail(id);if(onShelf&&row.status!=='APPROVED'&&row.status!=='OFF_SHELF')throw new BadRequestException('未审核通过的商品不允许上架');return this.prisma.product.update({where:{id},data:{status:onShelf?'ON_SHELF':'OFF_SHELF'}})}
 private async assertMerchantAndCategory(merchantId:string,categoryId:string){const[merchant,category]=await this.prisma.$transaction([this.prisma.merchant.findUnique({where:{id:merchantId}}),this.prisma.category.findUnique({where:{id:categoryId}})]);if(!merchant||merchant.status!=='ENABLED')throw new BadRequestException('商家不存在或已停用');if(!category||!category.enabled)throw new BadRequestException('分类不存在或已停用')}
 private composeDetail(content:string|undefined, fields:Record<string,unknown>){const labels:Record<string,string>={brand:'品牌',origin:'产地',material:'材质',processingMethod:'加工工艺',qualityStandard:'执行标准',unit:'计价单位',packaging:'包装方式',supplyCapacity:'供货能力',paymentTerms:'付款方式',shippingFrom:'发货地',services:'加工服务'};const lines=Object.entries(fields).filter(([,value])=>value).map(([key,value])=>`${labels[key]||key}：${value}`);return [content?.trim(),lines.length?`【产品参数】\n${lines.join('\n')}`:undefined].filter(Boolean).join('\n\n')||undefined}
}
